### ISSUE TITLE
can't connect to the PnPOnline

### ISSUE THREAD

**Issue by avsrot** [pnp/sp-site-designs-studio#11]
[55864357-ajax-search-pro-for-wordpress-live-search-plugin-license.txt](https://github.com/pnp/sp-site-designs-studio/files/4981956/55864357-ajax-search-pro-for-wordpress-live-search-plugin-license.txt)

I have installed the SharePointPnPPowershellOnline  as instructed :(

**Comment by ypcode** [comment]
Hello,

Please provide more information.
And I think your attached file might not be the intended one...

Best regards
Yannick

**Comment by avsrot** [comment]
sorry for the wrong attachment 😳
here is the right one
![Annotation 2020-07-27 152352](https://user-images.githubusercontent.com/55852486/88659837-5e33ed80-d0de-11ea-897c-659421ed343c.png)

**Comment by ypcode** [comment]
Hello,

I realized I left a typo in my recent update of the setup script...
Sorry for that. I'll fix it tomorrow and let you know :)

Best regards
Yannick

**Comment by ypcode** [comment]
Hello @avsrot,

I fixed the typo in the setup script, can you please get its latest version and try it again ?
Let me know if anything is blocking :)

Best regards,
Yannick

**Comment by avsrot** [comment]
sorry but I still get error
![Annotation 2020-08-03 185424](https://user-images.githubusercontent.com/55852486/89201942-e91f5700-d5ba-11ea-8adf-c5adcff7d9fd.png)

**Comment by ypcode** [comment]
Hello,

That is a really odd issue! The first time I see that...
Can you please provide the version of PnP PowerShell you use, I will try to reproduce it :)

Regards,
Yannick

**Comment by avsrot** [comment]
![Annotation 2020-08-03 224520](https://user-images.githubusercontent.com/55852486/89220936-17ad2a00-d5db-11ea-8d1e-c692b8df24b1.png)

**Comment by EmmanuelJahan** [comment]
Hi @avsrot ,
Probably due to network issue. Please refer to [this](https://www.koskila.net/fixing-security-reasons-dtd-prohibited-xml-document-issue/) article
Regards
Emmanuel

**Comment by avsrot** [comment]
@EmmanuelJahan 
Thanx, I read your blog carefully but befor trying one of 3 solutions you offered - suddenly the setup was running. but the the setup stopped with a new error:  
![image](https://user-images.githubusercontent.com/55852486/89572054-4e7c7d80-d831-11ea-9011-737062dec7f6.png)

**Comment by ypcode** [comment]
Thx for helping @EmmanuelJahan ! Really nice from you 👏

@avsrot , as the error message mentions, your tenant looks to have no app catalog installed. Can you please check in your admin center that the app catalog is created?

**Comment by avsrot** [comment]
BANG !!
ya hit the nail on it's head 👍
created an app catalog and all went smoooooth  :)

Thanx
Now I'll start playing

**Comment by ypcode** [comment]
Awesome ! Closing this issue. Let me know your feedback about the app :)
